guitars = [
    {
        "serial_number": "EL00001", 
        "price": 1299.99, 
        "builder": "Fender", 
        "model": "Stratocaster", 
        "guitar_type": "Electric", 
        "back_wood": "Mahogany", 
        "top_wood": "Alder" },
    {
        "serial_number": "EL00002", 
        "price": 899.99, 
        "builder": "Gibson", 
        "model": "Les Paul", 
        "guitar_type": "Electric", 
        "back_wood": "Mahogany", 
        "top_wood": "Maple" },
    {
        "serial_number": "AC00003", 
        "price": 1999.99, 
        "builder": "Martin", 
        "model": "OOO-DC Aura", 
        "guitar_type": "Acoustic", 
        "back_wood": "Indian Rosewood", 
        "top_wood": "Sitka Spruce"  },
    {
        "serial_number": "AC00004", 
        "price": 749.99, 
        "builder": "Yamaha", 
        "model": "FG800", 
        "guitar_type": "Acoustic", 
        "back_wood": "Nato", 
        "top_wood": "Spruce"    },
    {
        "serial_number": "AC00005", 
        "price": 1599.99, 
        "builder": "Taylor", 
        "model": "814ce DLX", 
        "guitar_type": "Acoustic", 
        "back_wood": "Indian Rosewood", 
        "top_wood": "Engelmann Spruce"  },
 ]